# notification-policies.yaml
---
apiVersion: 1

policies:
  - orgId: 1
    receiver: email-notifier
    group_by:
      - grafana_folder
      - alertname
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h

    mute_timings:
      - night-hours
      - weekend

    routes:
      - receiver: email-notifier
        matchers:
          - severity = warning

      - receiver: email-notifier
        matchers:
          - severity = critical
