global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "iot-simulator"
    static_configs:
      - targets: ["iot-simulator:9100"] # host port mapping

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"] # Prometheus itself
