# contact-points.yaml
apiVersion: 1

contactPoints:
  - orgId: 1
    name: email-notifier
    receivers:
      - uid: email1
        type: email
        disableResolveMessage: false
        settings:
          addresses: ${SMTP_USER}
          singleEmail: false
